export const RoleName = {
  CUSTOMER: 'CUSTOMER',
  SELLER: 'SELLER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  CUSTOMER_ADMIN: 'CUSTOMER_ADMIN',
  FASHION_ADMIN: 'FASHION_ADMIN',
  BEAUTY_HEALTH_ADMIN: 'BEAUTY_HEALTH_ADMIN',
  TECH_ADMIN: 'TECH_ADMIN',
  HOME_LIFESTYLE_ADMIN: 'HOME_LIFESTYLE_ADMIN',
  LEISURE_ADMIN: 'LEISURE_ADMIN',
  FOOD_BEVERAGE_ADMIN: 'FOOD_BEVERAGE_ADMIN',
  SHIPPER: 'SHIPPER',
  WAREHOUSE_SCANNER: 'WAREHOUSE_SCANNER',
} as const

export const HTTPMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
  OPTIONS: 'OPTIONS',
  HEAD: 'HEAD',
} as const
